language: node_js
sudo: false
branches:
  only:
    - development
    - master
node_js:
  - 8
install:
  - npm install
script:
  if: branch = master
  - echo "Building from master"
  if: branch = development
  - echo "Building from development"
  # - echo "Testing the echo step"
  # - npm run build:prod
  # - ls
  # - cd dist
  # - ls
