language: node_js
sudo: false
branches:
  only:
    - development
    - master
node_js:
  - 8
install:
  - npm install
script:
  - echo "test echo command development"
    on:
      branch: development
  - echo "test echo command master"
    on:
      branch: master
