language: node_js
sudo: false
branches:
  only:
    - development
    - master
node_js:
  - 8
install:
  - npm install
stages:
  - name: build_dev
    - npm run build:dev
    -  echo "running dev branch"
  if: branch = development
