language: node_js
sudo: false
branches:
  only:
    - development
    - master
node_js:
  - 8
install:
  - npm install
  - if [ $TRAVIS_BRANCH == 'master' ]; then npm run build:prod else npm run build:dev fi
script:
  - ls
  - echo $TRAVIS_BRANCH
  - echo "branch name^^"
