language: node_js
sudo: false
branches:
  only:
    - development
    - master
node_js:
  - 8
install:
  - npm install
script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; else npm run build:stg; fi
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "stg.dare.dev"
  skip_cleanup: true
  local_dir: dist
  on:
    branch: development
